package dev.radovanradivojevic.webrtcserver.model;

/**
 * Call message used for both offers and answers in WebRTC signaling
 *
 * An "offer" is sent by the caller with their SDP (capabilities and network info)
 * An "answer" is sent by the callee with their SDP in response
 *
 * Both use the same structure, only the "type" field differs.
 *
 * Example Offer JSON:
 * {"type": "offer", "to": "son", "sdp": "v=0\r\no=..."}
 *
 * Example Answer JSON:
 * {"type": "answer", "to": "dad", "sdp": "v=0\r\no=..."}
 */
public class CallMessage extends SignalingMessage {

    /**
     * Sender's userId
     * Who sent this offer/answer (populated by server)
     */
    private String from;

    /**
     * Recipient's userId
     * Who should receive this offer/answer
     */
    private String to;

    /**
     * Session Description Protocol data
     * Contains media capabilities, network addresses, encryption keys, etc.
     * This is a long text string generated by the WebRTC library
     */
    private String sdp;

    // Constructors
    public CallMessage() {
        super();
    }

    public CallMessage(String type, String to, String sdp) {
        super(type);
        this.to = to;
        this.sdp = sdp;
    }

    public CallMessage(String type, String from, String to, String sdp) {
        super(type);
        this.from = from;
        this.to = to;
        this.sdp = sdp;
    }

    // Getters and Setters
    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public String getSdp() {
        return sdp;
    }

    public void setSdp(String sdp) {
        this.sdp = sdp;
    }
}