package dev.radovanradivojevic.webrtcserver.model;

/**
 * ICE Candidate message for WebRTC connection negotiation
 *
 * ICE (Interactive Connectivity Establishment) candidates represent
 * possible network paths for connecting two devices. Devices exchange
 * multiple candidates and test them to find the best connection path.
 *
 * The candidate data is generated by the WebRTC library on Android.
 * The server doesn't need to understand it - just forward it!
 *
 * Example JSON:
 * {
 *   "type": "ice-candidate",
 *   "to": "son",
 *   "candidate": {
 *     "sdpMid": "1",
 *     "sdpMLineIndex": 1,
 *     "sdp": "candidate:1 1 udp 2130706431 192.168.100.11 52341 typ host"
 *   }
 * }
 */
public class IceCandidateMessage extends SignalingMessage {

    /**
     * Sender's userId
     * Who sent this ICE candidate (populated by server)
     */
    private String from;

    /**
     * Recipient's userId
     */
    private String to;

    /**
     * ICE candidate object generated by WebRTC library
     * Contains network path information and media line details
     */
    private IceCandidate candidate;

    // Constructors
    public IceCandidateMessage() {
        super("ice-candidate");
    }

    public IceCandidateMessage(String to, IceCandidate candidate) {
        super("ice-candidate");
        this.to = to;
        this.candidate = candidate;
    }

    public IceCandidateMessage(String from, String to, IceCandidate candidate) {
        super("ice-candidate");
        this.from = from;
        this.to = to;
        this.candidate = candidate;
    }

    // Getters and Setters
    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getTo() {
        return to;
    }

    public void setTo(String to) {
        this.to = to;
    }

    public IceCandidate getCandidate() {
        return candidate;
    }

    public void setCandidate(IceCandidate candidate) {
        this.candidate = candidate;
    }
}